
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIGIT DIVIDE LPAR MINUS PLUS RPAR SYMBOL TIMES whitespaceexp : exp PLUS exp\n           | exp MINUS exp\n           | exp TIMES exp\n           | exp DIVIDE exp\n    exp : DIGITexp : LPAR exp RPAR'
    
_lr_action_items = {'DIGIT':([0,3,4,5,6,7,],[2,2,2,2,2,2,]),'LPAR':([0,3,4,5,6,7,],[3,3,3,3,3,3,]),'$end':([1,2,9,10,11,12,13,],[0,-5,-1,-2,-3,-4,-6,]),'PLUS':([1,2,8,9,10,11,12,13,],[4,-5,4,4,4,4,4,-6,]),'MINUS':([1,2,8,9,10,11,12,13,],[5,-5,5,5,5,5,5,-6,]),'TIMES':([1,2,8,9,10,11,12,13,],[6,-5,6,6,6,6,6,-6,]),'DIVIDE':([1,2,8,9,10,11,12,13,],[7,-5,7,7,7,7,7,-6,]),'RPAR':([2,8,9,10,11,12,13,],[-5,13,-1,-2,-3,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,3,4,5,6,7,],[1,8,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp PLUS exp','exp',3,'p_exp_op','yaccpy.py',76),
  ('exp -> exp MINUS exp','exp',3,'p_exp_op','yaccpy.py',77),
  ('exp -> exp TIMES exp','exp',3,'p_exp_op','yaccpy.py',78),
  ('exp -> exp DIVIDE exp','exp',3,'p_exp_op','yaccpy.py',79),
  ('exp -> DIGIT','exp',1,'p_exp_digit','yaccpy.py',86),
  ('exp -> LPAR exp RPAR','exp',3,'p_par_exp','yaccpy.py',91),
]
